#!/bin/sh

TEMP_IMAGE="/tmp/i3lock.jpg"

# Colors
bg=1a1b26
fg=c0caf5
ring=15161e
wrong=f7768e
date=c0caf5
verify=9ece6a

default_lockscreen () {

    maim -d 0.3 -u ${TEMP_IMAGE}
    magick $TEMP_IMAGE -blur 5x4 $TEMP_IMAGE
    i3lock -n --force-clock -i $TEMP_IMAGE -e --indicator \
        --radius=30 --ring-width=60 --inside-color=$bg \
        --ring-color=$ring --insidever-color=$verify --ringver-color=$verify \
		--insidewrong-color=$wrong --ringwrong-color=$wrong --line-uses-inside \
		--keyhl-color=$verify --separator-color=$verify --bshl-color=$verify \
		--time-str="%H:%M" --time-size=140 --date-str="%a, %d %b" \
		--date-size=45 --verif-text="Verifying Password..." --wrong-text="Wrong Password!" \
		--noinput-text="" --greeter-text="Type the password to Unlock" --ind-pos="300:610" \
		--time-font="JetBrainsMono NF:style=Bold" --date-font="JetBrainsMono NF" --verif-font="JetBrainsMono NF" \
		--greeter-font="JetBrainsMono NF" --wrong-font="JetBrainsMono NF" --verif-size=23 \
		--greeter-size=23 --wrong-size=23 --time-pos="300:390" \
		--date-pos="300:450" --greeter-pos="300:780" --wrong-pos="300:820" \
		--verif-pos="300:655" --date-color=$date --time-color=$date \
		--greeter-color=$fg --wrong-color=$wrong --verif-color=$verify \
		--verif-pos="300:820" --pointer=default --refresh-rate=0 \
		--pass-media-keys --pass-volume-keys

}

default_lockscreen
rm "${TEMP_IMAGE}" > /dev/null 
