#!/bin/bash

# Uso: ./p10k_theme.sh [latte|frappe|macchiato|mocha]
THEME="${1:?}"
P10K_FILE="${HOME}/.p10k.zsh"

# 1. Definición de Paletas Catppuccin
declare -A ROSEWATER FLAMINGO PINK MAUVE RED MAROON PEACH YELLOW GREEN TEAL SKY SAPPHIRE BLUE LAVENDER TEXT SUBTEXT1 SUBTEXT0 OVERLAY2 OVERLAY1 OVERLAY0 SURFACE2 SURFACE1 SURFACE0 BASE MANTLE CRUST

case $THEME in
  latte)
    ROSEWATER="#dc8a78"; FLAMINGO="#dd7878"; PINK="#ea76cb"; MAUVE="#8839ef"; RED="#d20f39"; MAROON="#e64553"; PEACH="#fe640b"; YELLOW="#df8e1d"; GREEN="#40a02b"; TEAL="#179299"; SKY="#04a5e5"; SAPPHIRE="#209fb5"; BLUE="#1e66f5"; LAVENDER="#7287fd"; TEXT="#4c4f69"; SUBTEXT1="#5c5f77"; SUBTEXT0="#6c6f85"; OVERLAY2="#7c7f93"; OVERLAY1="#8c8fa1"; OVERLAY0="#9ca0b0"; SURFACE2="#acb0be"; SURFACE1="#bcc0cc"; SURFACE0="#ccd0da"; BASE="#eff1f5"; MANTLE="#e6e9ef"; CRUST="#dce0e8"
    ;;
  frappe)
    ROSEWATER="#f2d5cf"; FLAMINGO="#eebebe"; PINK="#f4b8e4"; MAUVE="#ca9ee6"; RED="#e78284"; MAROON="#ea999c"; PEACH="#ef9f76"; YELLOW="#e5c890"; GREEN="#a6d189"; TEAL="#81c8be"; SKY="#99d1db"; SAPPHIRE="#85c1dc"; BLUE="#8caaee"; LAVENDER="#babbf1"; TEXT="#c6d0f5"; SUBTEXT1="#b5bfe2"; SUBTEXT0="#a5adce"; OVERLAY2="#949cbb"; OVERLAY1="#838ba7"; OVERLAY0="#737994"; SURFACE2="#626880"; SURFACE1="#51576d"; SURFACE0="#414559"; BASE="#303446"; MANTLE="#292c3c"; CRUST="#232634"
    ;;
  macchiato)
    ROSEWATER="#f4dbd6"; FLAMINGO="#f0c6c6"; PINK="#f5bde6"; MAUVE="#c6a0f6"; RED="#ed8796"; MAROON="#ee99a0"; PEACH="#f5a97f"; YELLOW="#eed49f"; GREEN="#a6da95"; TEAL="#8bd5ca"; SKY="#91d7e3"; SAPPHIRE="#7dc4e4"; BLUE="#8aadf4"; LAVENDER="#b7bdf8"; TEXT="#cad3f5"; SUBTEXT1="#b8c0e0"; SUBTEXT0="#a5adcb"; OVERLAY2="#939ab7"; OVERLAY1="#8087a2"; OVERLAY0="#6e738d"; SURFACE2="#5b6078"; SURFACE1="#494d64"; SURFACE0="#363a4f"; BASE="#24273a"; MANTLE="#1e2030"; CRUST="#181926"
    ;;
  mocha)
    ROSEWATER="#f5e0dc"; FLAMINGO="#f2cdcd"; PINK="#f5c2e7"; MAUVE="#cba6f7"; RED="#f38ba8"; MAROON="#eba0ac"; PEACH="#fab387"; YELLOW="#f9e2af"; GREEN="#a6e3a1"; TEAL="#94e2d5"; SKY="#89dceb"; SAPPHIRE="#74c7ec"; BLUE="#89b4fa"; LAVENDER="#b4befe"; TEXT="#cdd6f4"; SUBTEXT1="#bac2de"; SUBTEXT0="#a6adc8"; OVERLAY2="#9399b2"; OVERLAY1="#7f849c"; OVERLAY0="#6c7086"; SURFACE2="#585b70"; SURFACE1="#45475a"; SURFACE0="#313244"; BASE="#1e1e2e"; MANTLE="#181825"; CRUST="#11111b"
    ;;
  *)
    echo "Tema no reconocido. Opciones: latte, frappe, macchiato, mocha"
    exit 1
    ;;
esac

echo "Aplicando tema: $THEME..."

apply_color() {
    local key=$1
    local color=$2
    sed -i "s|^test -g ${key}=.*|typeset -g ${key}='${color}'|g" "$P10K_FILE"
    sed -i "s|^\s*typeset -g ${key}=.*|  typeset -g ${key}='${color}'|g" "$P10K_FILE"
}

apply_color "POWERLEVEL9K_OS_ICON_BACKGROUND" "$MAUVE"
apply_color "POWERLEVEL9K_OS_ICON_FOREGROUND" "$BASE"

apply_color "POWERLEVEL9K_DIR_BACKGROUND" "$BLUE"
apply_color "POWERLEVEL9K_DIR_FOREGROUND" "$BASE"
apply_color "POWERLEVEL9K_DIR_SHORTENED_FOREGROUND" "$CRUST"
apply_color "POWERLEVEL9K_DIR_ANCHOR_FOREGROUND" "$BASE"

apply_color "POWERLEVEL9K_VCS_CLEAN_BACKGROUND" "$GREEN"
apply_color "POWERLEVEL9K_VCS_MODIFIED_BACKGROUND" "$YELLOW"
apply_color "POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND" "$GREEN"
apply_color "POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND" "$RED"
apply_color "POWERLEVEL9K_VCS_LOADING_BACKGROUND" "$SURFACE2"

apply_color "POWERLEVEL9K_STATUS_OK_FOREGROUND" "$GREEN"
apply_color "POWERLEVEL9K_STATUS_OK_BACKGROUND" "$SURFACE0"
apply_color "POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND" "$GREEN"
apply_color "POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND" "$SURFACE0"
apply_color "POWERLEVEL9K_STATUS_ERROR_FOREGROUND" "$RED"
apply_color "POWERLEVEL9K_STATUS_ERROR_BACKGROUND" "$SURFACE0"
apply_color "POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND" "$RED"
apply_color "POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND" "$SURFACE0"
apply_color "POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND" "$YELLOW"
apply_color "POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND" "$SURFACE0"

apply_color "POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND" "$GREEN"
apply_color "POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND" "$GREEN"
apply_color "POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND" "$GREEN"
apply_color "POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND" "$RED"
apply_color "POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND" "$RED"
apply_color "POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND" "$RED"

apply_color "POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND" "$BASE"
apply_color "POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND" "$YELLOW"

apply_color "POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND" "$BASE"
apply_color "POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND" "$PEACH"

apply_color "POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND" "$BASE"
apply_color "POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND" "$RED"
apply_color "POWERLEVEL9K_CONTEXT_FOREGROUND" "$BASE"
apply_color "POWERLEVEL9K_CONTEXT_BACKGROUND" "$LAVENDER"
apply_color "POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND" "$BASE"
apply_color "POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND" "$PEACH"

apply_color "POWERLEVEL9K_TIME_FOREGROUND" "$BASE"
apply_color "POWERLEVEL9K_TIME_BACKGROUND" "$LAVENDER"

langs=( "NODE_VERSION" "GO_VERSION" "RUST_VERSION" "DOTNET_VERSION" "PHP_VERSION" "JAVA_VERSION" "RBENV" "RVM" "FVM" "LUAENV" "JENV" "PLENV" "PERLBREW" "PHPENV" "SCALAENV" "HASKELL_STACK" )

for lang in "${langs[@]}"; do
    apply_color "POWERLEVEL9K_${lang}_FOREGROUND" "$BASE"
    apply_color "POWERLEVEL9K_${lang}_BACKGROUND" "$BLUE"
done

apply_color "POWERLEVEL9K_NODE_VERSION_BACKGROUND" "$GREEN"
apply_color "POWERLEVEL9K_RUST_VERSION_BACKGROUND" "$PEACH"
apply_color "POWERLEVEL9K_RUBY_BACKGROUND" "$RED"
apply_color "POWERLEVEL9K_PYTHON_BACKGROUND" "$BLUE"
apply_color "POWERLEVEL9K_GOLANG_BACKGROUND" "$SKY"

echo "¡Hecho! Recarga tu terminal o ejecuta: source ~/.p10k.zsh"
